# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from datetime import date, datetime
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer


class Ui_Title(object):

    def setupUi(self, Title):
        Title.setObjectName("Title")
        Title.resize(901, 622)

        self.centralwidget = QtWidgets.QWidget(Title)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -20, 901, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/money.jpg"))
        self.label.setObjectName("label")

        self.datelabel = QtWidgets.QLabel(self.centralwidget)
        self.datelabel.setGeometry(QtCore.QRect(30, 30, 371, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(18)
        font.setUnderline(True)
        self.datelabel.setFont(font)
        self.datelabel.setObjectName("datelabel")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(700, 50, 121, 41))
        self.addButton.setObjectName("addButton")
        self.addButton.clicked.connect(self.add_date)


        self.removeButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeButton.setGeometry(QtCore.QRect(700, 100, 121, 41))
        self.removeButton.setObjectName("removeButton")
        Title.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Title)
        self.statusbar.setObjectName("statusbar")
        Title.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(Title)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 901, 21))
        self.menuBar.setStyleSheet("background-color: rgb(172, 244, 255)")
        self.menuBar.setObjectName("menuBar")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setStyleSheet("background-color: rgb(199, 226, 255)")
        self.menuSettings.setObjectName("menuSettings")
        Title.setMenuBar(self.menuBar)
        self.actionSave = QtWidgets.QAction(Title)
        self.actionSave.setObjectName("actionSave")
        self.menuSettings.addAction(self.actionSave)
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(Title)
        QtCore.QMetaObject.connectSlotsByName(Title)

    def retranslateUi(self, Title):
        _translate = QtCore.QCoreApplication.translate
        Title.setWindowTitle(_translate("Title", "FinTrack Home"))
        self.datelabel.setText(_translate("Title", "Date:"))
        self.addButton.setText(_translate("Title", "Add Date"))
        self.removeButton.setText(_translate("Title", "Remove Date"))
        self.menuSettings.setTitle(_translate("Title", "Settings"))
        self.actionSave.setText(_translate("Title", "Save "))

    def add_date(self):
        # datetime object containing current date and time
        now = datetime.now()
        today = now.strftime("%d/%m/%Y %H:%M:%S")
        self.datelabel.setText("Date: " + today)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Title = QtWidgets.QMainWindow()
    ui = Ui_Title()
    ui.setupUi(Title)
    # Create a QTimer
    timer = QTimer()
    # Connect the timeout signal to the update_label method
    timer.timeout.connect(ui.add_date)
    # Start the timer with a 1000 ms (1 second) interval
    timer.start(1000)

    # Set fixed size to prevent resizing
    Title.setFixedSize(901, 622)

    Title.show()
    sys.exit(app.exec_())
